task: trajectory
wandb_group: bertram_test
run_name: bertram_traisformer_test
processed_dir: /dtu/blackhole/10/178320/preprocessed_1/final/
out_dir: data/checkpoints
window: 64
horizon: 12
features: [LAT, LON, SOG, COG, HEADING, ROT, NAV_STT, TIMESTAMP, MMSI]
model:
  name: traisformer
loss: huber
optimizer: adam
lr: 6e-4
batch_size: 96
epochs: 50