task: trajectory
wandb_group: bertram_test
run_name: bertram_tptrans_test
processed_dir: /Users/bertramhage/Development/preprocessed/
out_dir: data/checkpoints
window: 64
horizon: 12
features: [LAT, LON, SOG, COG, HEADING, ROT, NAV_STT, TIMESTAMP, MMSI]
model:
  name: traisformer
  d_model: 192
  nhead: 4
  enc_layers: 4
  dec_layers: 2
loss: huber
optimizer: adamw
lr: 0.0003
batch_size: 96
epochs: 5