task: trajectory
processed_dir: data/map_reduced/
out_dir: data/checkpoints/lite/
window: 64
horizon: 12
features: [LAT, LON, SOG, COG, HEADING, ROT, NAV_STT, TIMESTAMP, MMSI]
model:
  name: tptrans
  d_model: 512
  nhead: 8 # 4
  enc_layers: 8 # 4
  dec_layers: 4 # 2
  # dim_ff: 2048      # <— for compatibility with old checkpoints
  # use_posenc: false # <— if you want to exactly mirror old ckpts
loss: huber
optimizer: adamw
lr: 0.0003
batch_size: 96
epochs: 30